name: "Migrate (branch: prod)"

on:
  push:
    branches:
      - prod

jobs:
  production:
    strategy:
      matrix:
        database_urls: ${{ fromJSON(${{ secrets.DATABASE_URLS }}) }}
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: cd ui && yarn install --frozen-lockfile --silent

      - name: Run migrations
        run: cd ui && yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ matrix.database_urls }}
