name: Migrate

on:
  push:
    branches:
      - staging

jobs:
  production:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --frozen-lockfile --silent

      - name: Run migrations
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
